/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.16.3";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -I/usr/local/include -DHAVE_LIBSSL -DNDEBUG ";
const char *link_string = "gcc -I/usr/local/include -DHAVE_LIBSSL -DNDEBUG -liconv -lssl -lcrypto -lz -lz ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a";
